sonar.projectKey=ozlogger
sonar.projectName=OZlogger
sonar.sources=lib/
sonar.tests=tests/
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.coverage.exclusions=tests/**/*
sonar.javascript.node.maxspace=4096
sonar.projectVersion=0.3.1
